/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/LoginScreen` | `/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/kuji` | `/kuji`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cart` | `/cart`; params?: Router.UnknownInputParams; } | { pathname: `/components/AnimatedSplash`; params?: Router.UnknownInputParams; } | { pathname: `/constants/tamagui.config`; params?: Router.UnknownInputParams; } | { pathname: `/context/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/models/order`; params?: Router.UnknownInputParams; } | { pathname: `/models/prize`; params?: Router.UnknownInputParams; } | { pathname: `/models/series`; params?: Router.UnknownInputParams; } | { pathname: `/models/setting`; params?: Router.UnknownInputParams; } | { pathname: `/models/ticket`; params?: Router.UnknownInputParams; } | { pathname: `/models/user`; params?: Router.UnknownInputParams; } | { pathname: `/store/user-store`; params?: Router.UnknownInputParams; } | { pathname: `/products/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(screens)'}/LoginScreen` | `/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/kuji` | `/kuji`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/cart` | `/cart`; params?: Router.UnknownOutputParams; } | { pathname: `/components/AnimatedSplash`; params?: Router.UnknownOutputParams; } | { pathname: `/constants/tamagui.config`; params?: Router.UnknownOutputParams; } | { pathname: `/context/AuthContext`; params?: Router.UnknownOutputParams; } | { pathname: `/models/order`; params?: Router.UnknownOutputParams; } | { pathname: `/models/prize`; params?: Router.UnknownOutputParams; } | { pathname: `/models/series`; params?: Router.UnknownOutputParams; } | { pathname: `/models/setting`; params?: Router.UnknownOutputParams; } | { pathname: `/models/ticket`; params?: Router.UnknownOutputParams; } | { pathname: `/models/user`; params?: Router.UnknownOutputParams; } | { pathname: `/store/user-store`; params?: Router.UnknownOutputParams; } | { pathname: `/products/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(screens)'}/LoginScreen${`?${string}` | `#${string}` | ''}` | `/LoginScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/kuji${`?${string}` | `#${string}` | ''}` | `/kuji${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/cart${`?${string}` | `#${string}` | ''}` | `/cart${`?${string}` | `#${string}` | ''}` | `/components/AnimatedSplash${`?${string}` | `#${string}` | ''}` | `/constants/tamagui.config${`?${string}` | `#${string}` | ''}` | `/context/AuthContext${`?${string}` | `#${string}` | ''}` | `/models/order${`?${string}` | `#${string}` | ''}` | `/models/prize${`?${string}` | `#${string}` | ''}` | `/models/series${`?${string}` | `#${string}` | ''}` | `/models/setting${`?${string}` | `#${string}` | ''}` | `/models/ticket${`?${string}` | `#${string}` | ''}` | `/models/user${`?${string}` | `#${string}` | ''}` | `/store/user-store${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/LoginScreen` | `/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/kuji` | `/kuji`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cart` | `/cart`; params?: Router.UnknownInputParams; } | { pathname: `/components/AnimatedSplash`; params?: Router.UnknownInputParams; } | { pathname: `/constants/tamagui.config`; params?: Router.UnknownInputParams; } | { pathname: `/context/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/models/order`; params?: Router.UnknownInputParams; } | { pathname: `/models/prize`; params?: Router.UnknownInputParams; } | { pathname: `/models/series`; params?: Router.UnknownInputParams; } | { pathname: `/models/setting`; params?: Router.UnknownInputParams; } | { pathname: `/models/ticket`; params?: Router.UnknownInputParams; } | { pathname: `/models/user`; params?: Router.UnknownInputParams; } | { pathname: `/store/user-store`; params?: Router.UnknownInputParams; } | `/products/${Router.SingleRoutePart<T>}` | { pathname: `/products/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
